Added pre-compiled utils; Modified instructions for /boot

diff --git a/docs/NOTES b/docs/NOTES
--- a/docs/NOTES
+++ b/docs/NOTES
@@ -3,44 +3,52 @@ Disk setup:
 |                                 |
 |               sda               |
 |  _____________________________  |
-| |                             | |
-| |            sda1             | |
-| |          reiserfs           | |
-| |            5 GB             | |
-| |_____________________________| |
+| |                             | | This is your /boot directory.
+| |            sda1             | | We want this separate from the rest, as it
+| |          reiserfs           | | will occasionally need writing, whereas the
+| |           256 MB            | | base system will not. The short story for
+| |           /boot             | | this partitioning is that kernel upgrades
+| |_____________________________| | are a pain when you don't do this.
+|  _____________________________  |
+| |                             | | This is where you will install the base
+| |            sda2             | | system. Once you overlay the encrypted
+| |          reiserfs           | | drive, this will not change, so we advise
+| |          2.25 GB            | | that you customize the system a little. But
+| |             /               | | be aware that any traces you leave of your
+| |_____________________________| | activity will not get erased.
 |  _____________________________  |
 | |                             | |
-| |            sda2             | |
+| |            sda3             | |
 | |   LUKS encrypted partition  | |
 | |  _________________________  | |
-| | |                         | | |
-| | |       sda2_crypt        | | |
+| | |                         | | | We use LVM so that we can partition the
+| | |       sda3_crypt        | | | encrypted drive.
 | | |   LVM Physical Volume   | | |
 | | |  _____________________  | | |
 | | | |                     | | | |
 | | | |       crypt         | | | |
-| | | |    Volume Group     | | | |
+| | | |  LVM Volume Group   | | | |
 | | | |  _________________  | | | |
-| | | | |                 | | | | |
-| | | | |   crypt-swap    | | | | |
-| | | | |  Logical Volume | | | | |
-| | | | |      swap       | | | | |
-| | | | |      2 GB       | | | | |
+| | | | |                 | | | | | Since swap can potentially contain anything
+| | | | |   crypt-swap    | | | | | your memory can contain, it's a good idea
+| | | | |  Logical Volume | | | | | to encrypt that, as well, since it is not
+| | | | |      swap       | | | | | as volatile. I typically use a swap
+| | | | |      2 GB       | | | | | partition the same size as my memory.
 | | | | |_________________| | | | |
 | | | |  _________________  | | | |
+| | | | |                 | | | | | For crypt-drive, we recommend XFS as the
+| | | | |   crypt-drive   | | | | | filesystem, as it is the fastest to create.
+| | | | |  Logical Volume | | | | | Until the scripts we create below get more
+| | | | |       xfs       | | | | | flexible, it will be necessary to use the
+| | | | |                 | | | | | same filesystem as you will create when in
+| | | | |                 | | | | | duress, where speed will be a major
+| | | | |                 | | | | | discriminant between suspicious and
+| | | | |                 | | | | | acceptable behavior. XFS, JFS, or ReiserFS
+| | | | |                 | | | | | are all pretty quick. Ext* take quite a bit
+| | | | |                 | | | | | longer.
 | | | | |                 | | | | |
-| | | | |   crypt-drive   | | | | |
-| | | | |  Logical Volume | | | | |
-| | | | |    reiserfs     | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
-| | | | |                 | | | | |
+| | | | |                 | | | | | You should consider the size of this drive
+| | | | |                 | | | | | your effective hard disk space.
 | | | | |                 | | | | |
 | | | | |                 | | | | |
 | | | | |_________________| | | | |
@@ -49,18 +57,20 @@ Disk setup:
 | |_____________________________| |
 |_________________________________|
 
-This is the way Ubuntu sets it up when you go through the partitioning process
-on the server or alternate install disks. So we'll stick with these
+The names are those imposed by Ubuntu when you go through the partitioning
+process on the server or alternate install disks. So we'll stick with these
 conventions.
 
-The sizes are recommendations. On a desktop install, Ubuntu will easily require
-2.1GB. I typically use a swap partition the same size as my memory; you may
-want a larger or smaller. The important thing to remember is that you can more
-or less consider your first partition lost space, as nearly every file could be
-potentially be overwritten on your crypt-drive. So in the example above, your
-effective disk space is the size of your drive minus 7GB.
+The sizes are recommendations to give you about 100MB free on the base install
+and /boot on a desktop Ubuntu install.
+
+Before you begin, you should decide upon your duress password and your secure
+password. The secure password should be legitimately strong. The duress
+password should be convincingly strong.
 
 During the install, set your user's password to be your duress password.
+
+If any of what was just said was unclear, read the README for justification.
 
 After install:
 1) Upgrade kernel
@@ -75,14 +85,21 @@ After install:
 4) Uncomment /etc/apt/sources.list lines, if necessary
 5) Create /base, /crypt; mount crypt-drive on /crypt
 
-You will need the following utilities compiled as statically linked binaries:
-	- md5sum
-	- mkreiserfs (or a similar tool for your preferred filesystem)
+NOTE: We are assuming you don't want any custom settings on your base system.
+You can easily put off all of the following until you have customized your
+install. This is, in fact, recommended behavior. A fresh install is not only
+unpleasant to use, but easy to look for.
 
-You will need the following hand-rolled utilities
-	- getpass
-		char*getpass(char*);int printf(char*,...);
-		int main(int c,char**v){char*p=getpass("");printf("%s",p);}
+You will need mkfs.xfs (or a similar tool for another filesystem; choose for
+speed of creation, not brand loyalty) and mcrypt compiled as statically linked
+binaries.
+
+You will also need a simple program to read a string without echoing to screen
+and print the input without a trailing newline. The following will work,
+compiled with gcc (clearly not ISO/ANSI/$FOOSTANDARD compliant):
+
+	char*getpass(char*);int printf(char*,...);
+	main(){char*p=getpass("");printf("%s",p);}
 
 Prepare unionfs:
 
@@ -113,7 +130,7 @@ scripts/local:mountroot() should have these additional lines:
 	mkdir -p /base
 	mkdir -p /crypt
 	mount -t reiserfs -o ro /dev/sda1 /base
-	mount -t reiserfs -o rw /dev/mapper/crypt-drive /crypt
+	mount -t xfs -o rw /dev/mapper/crypt-drive /crypt
 	mount -t aufs -o rw,dirs=/crypt=rw:/base=ro aufs /root
 	mkdir -p /root/base
 	mkdir -p /root/crypt
@@ -132,15 +149,12 @@ scripts/local-top/cryptroot:setup_mapping()
 		echo -n "$PASS" | $cryptcreate > /dev/null 2>&1
 
 
-At this point, we should note that the changes we've made are not general
-changes. For instance, if you want to use ext3 and not reiserfs, your changes
-will need to reflect that.
-
 /etc/fstab should look something like this:
 
 proc			/proc	proc		defaults	0	0
 aufs			/	aufs		rw		0	0
-/dev/sda1		/base	reiserfs	ro,noauto	0	0
+/dev/sda1		/boot	reiserfs	ro,noauto	0	0
+/dev/sda2		/base	reiserfs	ro,noauto	0	0
 /dev/mapper/crypt-drive	/crypt	reiserfs	rw,noauto	0	0
 /dev/mapper/crypt-swap	none	swap		sw		0	0
 
@@ -148,6 +162,10 @@ Since sda1 and crypt-drive are being mounted by the initramfs scripts, we don't
 want to try mounting them again. It doesn't do anything bad, but it does make
 the word "fail" appear in red letters. But it's nice to have them around where
 we can see them, especially for remounting sda1 as rw and upgrading the kernel.
+
+At this point, we should note that the changes we've made are not general
+changes. For instance, if you want to use jfs and not xfs, your changes
+will need to reflect that.
 
 Since it's possible we've made a mistake, we want to be able to treat our
 system like normal and get back on our feet. Therefore, let's abuse Ubuntu's
@@ -177,7 +195,9 @@ data is there for the taking.
 Now, for the rest of us, it's time to get sneaky.
 
 You will need to place a statically linked binary of mkfs.xfs in the bin/ of
-your initrd working directory.
+your initrd working directory. (Add -static to your CFLAGS, and
+make with "make DEBUG=-DNDEBUG", as XFS may not compile properly with the
+default debug flag.)
 
 Rerun this line:
 	$ sudo cp /boot/initrd.img-2.6.24-1{9,6}-generic
@@ -284,3 +304,62 @@ And that's it. Time to make the initramfs:
 Reboot, and you're golden. The only real concern will be upgrading kernels,
 which will require rebuilding the initramfs. Just be sure to remember which
 old initramfs's are decoys.
+
+-------------------------------------------------------------------------------
+Statically linked binaries
+
+There are a couple of statically linked binaries needed for everything to work.
+Naturally, these particular programs present us with several problems. So here
+is a quick guide to compiling these yourself, in case our host doesn't
+presently have them compiled for your system.
+
+mkfs.xfs:
+A couple issues.
+
+The first is that, at least on my system, you can have libaio,
+but it still won't find lio_listio. Things still compile fine, so to keep
+configure from crashing, under the line:
+            echo 'FATAL ERROR: could not find a library with lio_listio.'
+comment out:
+            exit 1
+
+XFS by default compiles with the -DDEBUG flag, and the -DDEBUG flag causes make
+to try to compile a function that does not exist.
+
+$ export CFLAGS="-static"
+$ ./configure --enable-shared=no
+$ make DEBUG="-DNDEBUG"
+$ pushd mkfs
+$ gcc -static -o mkfs.xfs maxtrres.o proto.o xfs_mkfs.o \
+../libxfs/.libs/libxfs.a -luuid ../libdisk/.libs/libdisk.a -lrt -lpthread
+$ popd
+
+(That gcc line is the last line in the compilation of the mkfs directory, with
+the addition of -static.)
+
+
+mcrypt:
+First, you need statically compiled libmcrypt and libmhash. Fortunately, these
+are easy. Just compile with --enable-static. Then you'll need to remove some
+code from src/mcrypt.c and src/extra.c. Specifically, the parts surrounded by
+
+#ifdef HAVE_GETPWUID
+...
+#endif
+
+Of course, if there's an #else block, you'll leave its contents behind.
+
+Then, compile like so:
+
+$ export CFLAGS="-static -fno-stack-protection"
+$ ./configure --enable-static
+$ make
+$ pushd src
+$ gcc -static -fno-stack-protector -I/usr/local/include -Wall -o mcrypt \
+extra.o mcrypt.o keys.o random.o rndunix.o xmalloc.o functions.o errors.o \
+bits.o openpgp.o rndwin32.o environ.o getpass.o ufc_crypt.o popen.o classic.o \
+rfc2440.o gaaout.o  -lz /usr/local/lib/libmhash.a -L/usr/local/lib \
+/usr/local/lib/libmcrypt.a
+
+This one is slightly different from the last line for mcrypt, as .so is changed
+to .a, and `-static -fno-stack-protector' is inserted.
